#!/usr/bin/env ruby
# frozen_string_literal: true

require "fixturebot"

if defined?(::Rails::Application)
  require "fixturebot/rails"
  FixtureBot::Rails::CLI.start(ARGV)
else
  FixtureBot::CLI.start(ARGV)
end
