#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "fixturebot/rails"
  FixtureBot::Rails::CLI.start(ARGV)
rescue LoadError
  require "fixturebot"
  require "fixturebot/cli"
  FixtureBot::CLI.start(ARGV)
end
